export enum MARKETS {
  'BNBUSDT' = 'BNB/USDT',
  'BTCUSDT' = 'BTC/USDT',
  'ETHUSDT' = 'ETH/USDT',
  'MATICUSDT' = 'MATIC/USDT',
  'NEARUSDT' = 'NEAR/USDT',
  'PENDLEUSDT' = 'PENDLE/USDT',
  'RNDRUSDT' = 'RNDR/USDT',
  'SOLUSDT' = 'SOL/USDT'
}

